spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ramli_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: saloum
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # update, create, validate, none selon usage
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      write-dates-as-timestamps: false  # Pour bien gérer OffsetDateTime, LocalDateTime au format ISO8601

jwt:
  secret: "3WdKDpcnAskKTvuQ3kew1dJdFtcfJRRIvlCg4pusU2U="
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

mail:
  host: smtp.gmail.com
  port: 587
  username: sensaloumdev@gmail.com
  password: iloe dyfb jioi dmgz
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG*
    org.springframework.mail: DEBUG
    org.springframework.boot.autoconfigure.mail: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE

server:
  port: 22000


